### ISSUE TITLE
A* Search: "SyntaxError: inconsistent use of tabs and spaces in indentation"

### ISSUE THREAD

**Issue by RedRaspberry** [MUSoC/Visualization-of-popular-algorithms-in-Python#32]
Here's the output from my console:

>>> %Run a_star_search.py
  File "/Users/student/Downloads/Visualization-of-popular-algorithms-in-Python-master/A* Search/a_star_search.py", line 40
    final_path = []
                  ^
SyntaxError: inconsistent use of tabs and spaces in indentation

Any idea as to what i'm doing wrong, or is this a problem with the program itself?

Thanks

**Comment by kartikarora** [comment]
Python requires proper indentation for the code to work. Indentation level also defines the scope in python, unlike `{}` in C++, Java etc. The file probably has an indentation issue, I'll have a look at the file.

**Comment by kartikarora** [comment]
@RedRaspberry  Just ran the file as it is, seems to be fine. Double check your copy of the file, there might be spaces and tab indentation mixed together in the same file.

@vrush03 @shettyabhi48 You might wanna see this.

**Comment by sidkothiyal** [comment]
Fixed

**Comment by kartikarora** [comment]
When? How? What? @sidkothiyal

**Comment by sidkothiyal** [comment]
Lol! Right now @kartikarora

**Comment by xiangjjj** [comment]
I encountered the same space and tab problem in `dijsktras.py`.
