### ISSUE TITLE
Visualization-of-popular-algorithms-in-Python/Prim's/prims.py

### ISSUE THREAD

**Issue by nenadhristov** [MUSoC/Visualization-of-popular-algorithms-in-Python#36]
i am new in python so using this code i got this error:
Traceback (most recent call last):
  File "C:/Users/Nano_/PycharmProjects/graph/graph.py", line 76, in <module>
    G = CreateGraph()
  File "C:/Users/Nano_/PycharmProjects/graph/graph.py", line 58, in CreateGraph
    if wtMatrix[i][j] > 0 :
TypeError: 'map' object is not subscriptable

**Comment by nenadhristov** [comment]
ohh just translate it to python3 it works good !

**Comment by pavithrahareddy** [comment]
Hi I'm very new to python coding and am getting the same above error. Can u please help me about what is suppose to be done to remove the error
