### ISSUE TITLE
Hi I'm very new to python coding and am getting the same above error. Can u please help me about what is suppose to be done to remove the error

### ISSUE THREAD

**Issue by pavithrahareddy** [MUSoC/Visualization-of-popular-algorithms-in-Python#39]
I am getting the same above error. Can u please help me about what is suppose to be done to remove the error

_Originally posted by @pavithrahareddy in https://github.com/MUSoC/Visualization-of-popular-algorithms-in-Python/issues/36#issuecomment-614395031_

**Comment by pavithrahareddy** [comment]
File "C:/Users/Nano_/PycharmProjects/graph/graph.py", line 76, in
G = CreateGraph()
File "C:/Users/Nano_/PycharmProjects/graph/graph.py", line 58, in CreateGraph
if wtMatrix[i][j] > 0 :
TypeError: 'map' object is not subscriptable

**Comment by ykl7** [comment]
As in #36 it needs to be translated to Python 3

**Comment by pavithrahareddy** [comment]
Sir ,
     I am really not understanding what you are trying to say. Can you please explain me in detail.
